routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'dashboard/', 'as' => 'dashboard.', 'namespace' => 'Dashboard\\'], function()
{
    Route::get('home',                  ['as' => 'home',          'uses' => 'DashboardController@index']);

    Route::get('slider',                ['as' => 'slider',        'uses' => 'SliderController@index']);
    Route::get('slider/create',         ['as' => 'slider.create', 'uses' => 'SliderController@create']);
    Route::post('slider/store',         ['as' => 'slider.store',  'uses' => 'SliderController@store']);
    Route::get('slider/show/{id}',      ['as' => 'slider.show',   'uses' => 'SliderController@show']);
    Route::get('slider/edit/{id}',      ['as' => 'slider.edit',   'uses' => 'SliderController@edit']);
    Route::put('slider/update/{id}',    ['as' => 'slider.update', 'uses' => 'SliderController@update']);
    Route::delete('slider/delete/{id}', ['as' => 'slider.delete', 'uses' => 'SliderController@destroy']);

    Route::get('programs',                ['as' => 'programs',        'uses' => 'ProgramController@index']);
    Route::get('programs/create',         ['as' => 'programs.create', 'uses' => 'ProgramController@create']);
    Route::post('programs/store',         ['as' => 'programs.store',  'uses' => 'ProgramController@store']);
    Route::get('programs/show/{id}',      ['as' => 'programs.show',   'uses' => 'ProgramController@show']);
    Route::get('programs/edit/{id}',      ['as' => 'programs.edit',   'uses' => 'ProgramController@edit']);
    Route::put('programs/update/{id}',    ['as' => 'programs.update', 'uses' => 'ProgramController@update']);
    Route::delete('programs/delete/{id}', ['as' => 'programs.delete', 'uses' => 'ProgramController@destroy']);

    Route::get('courses',                ['as' => 'courses',        'uses' => 'CourseController@index']);
    Route::get('courses/create/{id}',         ['as' => 'courses.create', 'uses' => 'CourseController@create']);
    Route::post('courses/store',         ['as' => 'courses.store',  'uses' => 'CourseController@store']);
    Route::get('courses/show/{id}',      ['as' => 'courses.show',   'uses' => 'CourseController@show']);
    Route::get('courses/edit/{id}',      ['as' => 'courses.edit',   'uses' => 'CourseController@edit']);
    Route::put('courses/update/{id}',    ['as' => 'courses.update', 'uses' => 'CourseController@update']);
    Route::delete('courses/delete/{id}', ['as' => 'courses.delete', 'uses' => 'CourseController@destroy']);

    Route::get('level',                ['as' => 'level',        'uses' => 'LevelController@index']);
    Route::get('level/create',         ['as' => 'level.create', 'uses' => 'LevelController@create']);
    Route::post('level/store',         ['as' => 'level.store',  'uses' => 'LevelController@store']);
    Route::get('level/show/{id}',      ['as' => 'level.show',   'uses' => 'LevelController@show']);
    Route::get('level/edit/{id}',      ['as' => 'level.edit',   'uses' => 'LevelController@edit']);
    Route::put('level/update/{id}',    ['as' => 'level.update', 'uses' => 'LevelController@update']);
    Route::delete('level/delete/{id}', ['as' => 'level.delete', 'uses' => 'LevelController@destroy']);

    Route::get('contact',                ['as' => 'contact',        'uses' => 'ContactController@index']);
    Route::get('contact/create',         ['as' => 'check',          'uses' => 'ContactController@create']);
    Route::post('contact/store',         ['as' => 'contact.store',  'uses' => 'ContactController@store']);
    Route::get('contact/show/{id}',      ['as' => 'contact.show',   'uses' => 'ContactController@show']);
    Route::delete('contact/delete/{id}', ['as' => 'contact.delete', 'uses' => 'ContactController@destroy']);
    Route::post('contact/reply/{id}',     ['as' => 'contact.reply', 'uses' => 'ContactController@reply']);

    Route::get('album',                ['as' => 'album',        'uses' => 'AlbumController@index']);
    Route::get('album/create',         ['as' => 'album.create', 'uses' => 'AlbumController@create']);
    Route::post('album/store',         ['as' => 'album.store',  'uses' => 'AlbumController@store']);
    Route::get('album/show/{id}',      ['as' => 'album.show',   'uses' => 'AlbumController@show']);
    Route::get('album/edit/{id}',      ['as' => 'album.edit',   'uses' => 'AlbumController@edit']);
    Route::put('album/update/{id}',    ['as' => 'album.update', 'uses' => 'AlbumController@update']);
    Route::delete('album/delete/{id}', ['as' => 'album.delete', 'uses' => 'AlbumController@destroy']);

    Route::get('pictures',                ['as' => 'pictures',        'uses' => 'PictureController@index']);
    Route::get('pictures/create/{id}',    ['as' => 'pictures.create', 'uses' => 'PictureController@create']);
    Route::post('pictures/store',         ['as' => 'pictures.store',  'uses' => 'PictureController@store']);
    Route::get('pictures/show/{id}',      ['as' => 'pictures.show',   'uses' => 'PictureController@show']);
    Route::get('pictures/edit/{id}',      ['as' => 'pictures.edit',   'uses' => 'PictureController@edit']);
    Route::put('pictures/update/{id}',    ['as' => 'pictures.update', 'uses' => 'PictureController@update']);
    Route::delete('pictures/delete/{id}', ['as' => 'pictures.delete', 'uses' => 'PictureController@destroy']);

    Route::get('video',                ['as' => 'video',        'uses' => 'VideoController@index']);
    Route::get('video/create',         ['as' => 'video.create', 'uses' => 'VideoController@create']);
    Route::post('video/store',         ['as' => 'video.store',  'uses' => 'VideoController@store']);
    Route::get('video/show/{id}',      ['as' => 'video.show',   'uses' => 'VideoController@show']);
    Route::get('video/edit/{id}',      ['as' => 'video.edit',   'uses' => 'VideoController@edit']);
    Route::put('video/update/{id}',    ['as' => 'video.update', 'uses' => 'VideoController@update']);
    Route::delete('video/delete/{id}', ['as' => 'video.delete', 'uses' => 'VideoController@destroy']);

    Route::get('page',                ['as' => 'page',        'uses' => 'PageController@index']);
    Route::get('page/create',         ['as' => 'page.create', 'uses' => 'PageController@create']);
    Route::post('page/store',         ['as' => 'page.store',  'uses' => 'PageController@store']);
    Route::get('page/show/{id}',      ['as' => 'page.show',   'uses' => 'PageController@show']);
    Route::get('page/edit/{id}',      ['as' => 'page.edit',   'uses' => 'PageController@edit']);
    Route::put('page/update/{id}',    ['as' => 'page.update', 'uses' => 'PageController@update']);
    Route::delete('page/delete/{id}', ['as' => 'page.delete', 'uses' => 'PageController@destroy']);

    Route::get('about',                ['as' => 'about',        'uses' => 'AboutController@index']);
    Route::get('about/create',         ['as' => 'about.create', 'uses' => 'AboutController@create']);
    Route::post('about/store',         ['as' => 'about.store',  'uses' => 'AboutController@store']);
    Route::get('about/show/{id}',      ['as' => 'about.show',   'uses' => 'AboutController@show']);
    Route::get('about/edit/{id}',      ['as' => 'about.edit',   'uses' => 'AboutController@edit']);
    Route::put('about/update/{id}',    ['as' => 'about.update', 'uses' => 'AboutController@update']);
    Route::delete('about/delete/{id}', ['as' => 'about.delete', 'uses' => 'AboutController@destroy']);

    Route::get('settings',                ['as' => 'settings',        'uses' => 'SettingController@index']);
    Route::get('settings/create',         ['as' => 'settings.create', 'uses' => 'SettingController@create']);
    Route::post('settings/store',         ['as' => 'settings.store',  'uses' => 'SettingController@store']);
    Route::get('settings/show/{id}',      ['as' => 'settings.show',   'uses' => 'SettingController@show']);
    Route::get('settings/edit/{id}',      ['as' => 'settings.edit',   'uses' => 'SettingController@edit']);
    Route::put('settings/update/{id}',    ['as' => 'settings.update', 'uses' => 'SettingController@update']);
    Route::delete('settings/delete/{id}', ['as' => 'settings.delete', 'uses' => 'SettingController@destroy']);

    Route::get('enquiry',                ['as' => 'enquiry',        'uses' => 'EnquiryController@index']);
    Route::get('enquiry/create',         ['as' => 'enquiry.create', 'uses' => 'EnquiryController@create']);
    Route::post('enquiry/store',         ['as' => 'enquiry.store',  'uses' => 'EnquiryController@store']);
    Route::get('enquiry/show/{id}',      ['as' => 'enquiry.show',   'uses' => 'EnquiryController@show']);
    Route::get('enquiry/edit/{id}',      ['as' => 'enquiry.edit',   'uses' => 'EnquiryController@edit']);
    Route::put('enquiry/update/{id}',    ['as' => 'enquiry.update', 'uses' => 'EnquiryController@update']);
    Route::delete('enquiry/delete/{id}', ['as' => 'enquiry.delete', 'uses' => 'EnquiryController@destroy']);
});
    
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $fillable = ['address', 'email', 'number1', 'number2', 'links'];
}

app/Http/Controllers/Dashboard/AboutController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\About;
use App\Http\Requests\About\AddValidation;
use App\Http\Requests\About\EditValidation;

class AboutController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $about = About::all();
        return view('dashboard.about.index',compact('about'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.about.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddValidation $request)
    {
        About::create($request->all());
        return redirect()->route('dashboard.about');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $about = About::findorFail($id);
        return view('dashboard.about.show',compact('about'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $about = About::findorFail($id);
        return view('dashboard.about.edit',compact('about'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditValidation $request, $id)
    {
        About::findorFail($id)->update($request->all());
        return redirect()->route('dashboard.about');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        About::findorFail($id)->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/AlbumController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Album;
use App\Models\Picture;
use App\Http\Requests\Album\AddValidation;
use App\Http\Requests\Album\EditValidation;

class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums = Album::all();
        $pictures = Picture::all()->where('cover', '1');
        return view('dashboard.album.index',compact('albums','pictures'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.album.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddValidation $request)
    {
        Album::create($request->all());
        return redirect()->route('dashboard.album');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $album = Album::findorFail($id);
        $pictures = Picture::all();
        return view('dashboard.album.show',compact('album','pictures'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $album = Album::findorFail($id);
        return view('dashboard.album.edit',compact('album'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditValidation $request, $id)
    {
        $album = Album::findorFail($id);
        $album->title = $request->get('title');
        $album->save();

        return redirect()->route('dashboard.album');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $album = Album::findorFail($id);
        $album->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/ContactController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Mail\ContactMail;
use App\Mail\ReplyMail;
use App\Models\Contact;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Redirect;
use App\Http\Requests\Contact\AddValidation;
use App\Http\Requests\Contact\EditValidation;

class ContactController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }
    
    // public function messages()
    // {
    //     return view('dashboard.includes.message',compact('contacts'));
    // }
    public function index()
    {
        $messages = Contact::all();
        return view('dashboard.contact.index',compact('messages'));
    }
    public function create()
    {
        return view('check');
    }

    public function store(AddValidation $request)
    {
       $contact = Contact::create($request->all());
       
       Mail::to(ENV('MAIL_USERNAME'))->send(new ContactMail($contact));
       
       return redirect()->back();
       
    } 

    public function show($id)
    {
        $contact = Contact::findorFail($id);
        $contact->status = 1;
        $contact->update();
        return view('dashboard.contact.show',compact('contact'));
    }
    
    public function destroy($id)
    {
        $contact = Contact::findorFail($id);
        $contact->delete();
        
        return redirect()->route('dashboard.home');
    }
    
    public function reply(EditValidation $request, $id)
    {
        $contact = Contact::findorFail($id);
        $reply = $request->get('reply');

        Mail::to($contact->email)->send(new ReplyMail($reply));
        return redirect()->back()->with('success','Sent!');
    } 
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        return view('dashboard.home.index');
    }
}

resources/views/dashboard/settings/create.blade.php
@extends('dashboard.master')

@section('title')
    Settings
@endsection

@section('content')
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Add something in setting</h3>
        </div>
        <div class="card-body">
            <div class="form-group">
                {!! Form::open(['route' => ['dashboard.settings.store'], 'enctype'=>'multipart/form-data']) !!}
                    @include('dashboard.settings.common.form')
                {!! Form::close() !!}
            </div>      
        </div>
    </div>
@endsection

resources/views/dashboard/settings/edit.blade.php
@extends('dashboard.master')

@section('title')
    Settings
@endsection

@section('content')
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Edit some settings</h3>
        </div>
        <div class="card-body">
            <div class="form-group">
                {!! Form::model($settings, ['route' => ['dashboard.settings.update',$page->id], 'enctype'=>'multipart/form-data']) !!}
                    @method('PUT')
                    @include('dashboard.settings.common.form')
                {!! Form::close() !!}
            </div>      
        </div>
    </div>            
@endsection

resources/views/dashboard/settings/index.blade.php
@extends('dashboard.master')

@section('title')
    Settings
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"> Settings </h3>
            <h6 class="float-right"><a href="{{route('dashboard.settings.create')}}" class="btn btn-info btn-sm">Create a new setting </a> </h6>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped text-center">
                <thead>
                    <tr>
                        <th>Address</th>
                        <th>Email</th>
                        <th>Number-1</th>
                        <th>Number-2</th>
                        <th>Social Network</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($settings as $setting)
                        <tr>
                            <td> {{$setting->address}} </td>
                            <td> {{$setting->email}} </td>
                            <td> {{$setting->number1}} </td>
                            <td> {{$setting->number2}} </td>
                            <td> {!! $setting->links !!} </td>
                            <td>
                                <a href="{{route('dashboard.settings.edit',$settings->id)}}" class="btn btn-primary" title="Edit"> <i class="fa fa-edit"></i> </a>
                                <button class="btn btn-danger" data-toggle = "modal" data-target = "#settings-{{$settings->id}}" title="Delete"><i class="fa fa-trash"></i></button>
                                <div class="modal fade" id="settings-{{$settings->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Are you sure?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                {!! Form::model($settings, ['route' => ['dashboard.settings.delete',$settings->id]]) !!}
                                                    @method('DELETE')
                                                     {!! Form::submit('Delete', ['class' => 'btn btn-danger float-right']) !!}
                                                {!! Form::close() !!}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection